### ISSUE TITLE
VC panels not getting mouse events

### ISSUE THREAD

**Issue by GLS-SSV** [orbitersim/orbiter#104]
VC panels not getting clicks

Did some debugging regarding the issue of clbkVCMouseEvent() not being called when a click is made on a panel and here are my findings.

It seems that if oapiVCSetAreaClickmode_Quadrilateral() is given all 4 points exactly contained in a plane, the calculations at VirtualCockpit::SetClickZone_Quadrilateral() (VCockpit.cpp:300) fail. My half-forgotten algebra knowledge tells me that matrix P1 (and also P2) doesn't have full rank when the 4 points are co-planar thus it will be singular, which actually gets flagged in function qrdcmp(). After that, the function qrsolv() is called which divides by 0, and returns "-nan(ind)". When the click is made, the "-nan(ind)" in the math means the checks to determine if the click is on that panel will fail.

When this occurs or not seems to be "floating-point numerical coincidence", as co-planar points that initially produce a non-singular matrix, after adding an offset from a c.g. shift will produce a singular matrix.

My, again, half-forgotten algebra knowledge led me to add an offset (at the addon level) to point 4 (this one doesn't get used in the plane equation), normal to the panel plane, to "force" full rank in the matrix, and in initial testing the panels get the clicks, with the correct coordinates.

Not sure if this could be considered a final solution, but IMO the code should handle the situation of the 4 points being co-planar.

**Comment by mschweiger** [comment]
Thanks for looking into this. I have now submitted a fix in branch https://github.com/orbitersim/orbiter/tree/104-clickzone_quadrilateral_fail. This checks for a co-planar 4th point and offsets it along the plane normal if required, as you suggest.
Can you please check if this fixes the problem? If you are happy I'll merge the branch.

**Comment by GLS-SSV** [comment]
After a couple of days clicking everywhere I still haven't found another case of failing clicks. Green light for merge from my end.
Thanks!
