### ISSUE TITLE
Calculation of normals in Shipedit

### ISSUE THREAD

**Issue by GLS-SSV** [orbitersim/orbiter#129]
The calculation of vertex normals in Shipedit might not be the most correct. Currently the normal of a vertex is the average of the normals of each triangle that is built with that vertex.
But consider this shape:
![image](https://user-images.githubusercontent.com/88407628/132006720-d57f8e2d-e28e-43a5-afd7-db83f0aaa161.png)
In that calculation, the normal of the seleted vertex will be the average of 2 "up" vectors and 1 "side" vector, thus resulting in a normal 2/3 "up" and 1/3 "side", when visually it should be 50/50. So maybe a better way to calculate the vertex normals should not consider "duplicate" triangle normals in the average.

IMO, some thought should be given to this: Is it correct? Does it result in wrong normals in other shapes? Does it affect the graphic engines?

**Comment by mschweiger** [comment]
What about factoring in the angle of the triangle at the vertex point? This would make sense because a triangle that contributes a larger angle at the vertex point has a bigger share of the surface bordering that vertex. So in your case, the two top triangles would contribute 2 * pi/4 * up, while the side triangle would contribute pi/2 * side, so equal weights.

**Comment by GLS-SSV** [comment]
That also seems a good solution, and it is probably easier to implement.


BTW:  PR #128 is not related to this, it adds missing normalization of the calculated normal vector, while this is "how to calculate the normal vector".

**Comment by mschweiger** [comment]
@GLS-SSV : Does  6fe31d9 look right to you?

**Comment by GLS-SSV** [comment]
Looking at the code without running, it seems good! I'll run some meshes past it tonight.

Just noticed one more thing that is "unfair". I assume the cross product on line 458 is done to filter the contribution of thin triangles which might have "uneven" normals, but as it stands this depends on which vertex is picked: one vertex might be on a "pointy" end of a thin triangle and it will fail the test on line 467, but if another vertex is used, on a wide area of the same thin triangle, then it will pass the test.
IMO the cross product should be calculated for all 3 corners, and then either (1) take all 3 values and decide if the triangle is "thin", or (2) use the values individually and decide for each vertex if this triangle is wide enough at the vertex to contribute.
I vote for (1) as it fits better with the idea of filtering "uneven" normals, with a test being `((len1 >= eps) && (len2 >= eps) && (len3 >= eps))`.

**Comment by mschweiger** [comment]
The cross product in 458 is really just to get the normal direction of the triangle. Once the direction is normalised (in 468) this should be independent of which vertex was selected. The only reason for the check in line 467 is to a avoid a division by (or close to) 0 in case the triangle is degenerate with three (nearly) collinear vertices. It is true that the two other angles could be ok for generating the normal, so I could just try them if the first one fails, but the triangle would still be pathological (two vertices near identical), so I thought it was ok to just skip it.

**Comment by GLS-SSV** [comment]
Ok, that makes sense. (I need to sleep more...)

So, I've put some meshes thru the new logic and it seems ok!

**Comment by mschweiger** [comment]
Excellent! I've now applied the same updated logic for code in the meshc utility and in the Orbiter core mesh implementation. I have also rearranged the code slightly to avoid acos computations when not required. Performance is probably not critical for Shipedit and meshc, but could be for the Orbiter core instance when normals are computed on the fly for meshes that don't define them.

This should still work the same as before, but just to make sure, if you have time, can you try your test cases again with the latest commits? If it's all good I'll merge the branch.

**Comment by GLS-SSV** [comment]
Seems OK from here!
