### ISSUE TITLE
Deleting vessel cause crash when running with external graphic client

### ISSUE THREAD

**Issue by spacex15** [orbitersim/orbiter#145]
Testing on the d3d9client branch

The external graphic client clbkDeleteVessel is never called by orbiter core

I got a crash running in debug mode because of this

I suggest to change the following code in orbiter.cpp

#ifdef INLINEGRAPHICS
			oclient->clbkDeleteVessel ((OBJHANDLE)vessel);
#endif

to

#ifdef INLINEGRAPHICS
			oclient->clbkDeleteVessel ((OBJHANDLE)vessel);
#else
			if(gclient)
			    gclient->clbkDeleteVessel((OBJHANDLE)vessel);
#endif

same problem exists with other virtual module functions 

Or maybe the d3d9client  should register these functions ?

**Comment by riojax** [comment]
Please, can you retest it?
