### ISSUE TITLE
Vulkan renderer

### ISSUE THREAD

**Issue by uranuspucksaxophone** [orbitersim/orbiter#153]
Vulkan is the best graphics API, when compared to DirectX and OpenGL.

Pros:
- Very high performance
- Open source
- Good graphics fidelity

Cons:
- Very hard to implement

In my humble opinion, a project like this could benefit from Vulkan,
as the default rendering API.

Related to issue #8

**Comment by jarmonik** [comment]
Sounds great, can you create one ?

**Comment by uranuspucksaxophone** [comment]
Please, Can you reopen the issue?, on the other hand, I cannot create a Vulkan engine, sorry.

**Comment by supersonic71** [comment]
The latest release of Godot (4.0 alpha) comes with Vulkan support. 
I have worked on small Godot projects before. If anyone wants to create a Visualization client using Godot, I'll be glad to contribute.
One more pro: cross platform support (Linux).

**Comment by jarmonik** [comment]
I am pretty sure everybody is a very well aware of that Vulkan renderer would be nice but as long as there are no developer, mere requests doesn't help much. I did start preparing D3D9Client for a transition to Vulkan but learned that there is a modern OpenGL rendered (Skybolt) partially in a working order already and I didn't see a point to start competing with it with a Vulkan. Meanwhile I continue developing the D3D9.

**Comment by supersonic71** [comment]
Thanks for the update jarmonik. Someone on reddit mentioned the D3D9 client works on Linux using Wine, will give it a try.

**Comment by Miner34dev** [comment]
> Thanks for the update jarmonik. Someone on reddit mentioned the D3D9 client works on Linux using Wine, will give it a try.

That's fully true, i'm using orbiter 2016 on Ubuntu!
