### ISSUE TITLE
vs 2022 error

### ISSUE THREAD

**Issue by weather-tracker** [orbitersim/orbiter#155]
getting an error when trying to compile that it cannot find vs 2019.
have several more errors unrelated to.

**Comment by weather-tracker** [comment]
Visual Studio 16 2019
  
    could not find any instance of Visual Studio.

i am using vs 2022

**Comment by CaptainSwag101** [comment]
Hello, I had the same issue, you can fix this by editing `Utils/CMakeLists.txt` and changing the text "Visual Studio 16 2019" to "Visual Studio 17 2022", and then deleting and regenerating the CMake Cache via Visual Studio, performing Clean All, and then your build should work properly.

**Comment by jarmonik** [comment]
"Visual Studio 16 2019" is no longer mentioned in Utils/CMakeLists.txt
Assumed to be fixed. Reopen if problem still exists.
