### ISSUE TITLE
crash in bool PlanetarySystem::DelBody (Body *_body)

### ISSUE THREAD

**Issue by spacex15** [orbitersim/orbiter#175]
I get an occasional crash in

bool PlanetarySystem::DelBody (Body *_body)
{
	DWORD i, j, k;
	Body **tmp;
	for (i = 0; i < nbody; i++)
		if (body[i] == _body) break;
	if (i == nbody) return false;
	delete []body[i]; // delete actual body
	if (body[i]->s0) body[i]->s0 = NULL;    -- CRASH HERE
	if (body[i]->s1) body[i]->s1 = NULL;
	if (body[i]) body[i] = NULL;
	if (nbody > 1) {
		tmp = new Body*[nbody-1]; TRACENEW
		for (j = k = 0; j < nbody; j++)
			if (j != i) tmp[k++] = body[j];
	} else tmp = 0;
	delete []body;
	body = tmp;
	nbody--;
	return true;
}

I really do not understand this code
delete []body[i];
and then access if (body[i]->s0) ??

**Comment by riojax** [comment]
nice catch, I will check it

**Comment by riojax** [comment]
Clearly the assignment order was wrong, now it must to work. Also the null assignment was removed, due that a competent compiler must to do that on delete. Please, can you test the PR #177 to check if it's fixed?

**Comment by spacex15** [comment]
Hi 
sorry for the delay in testing
I see that the fix is already merged
Unfortunately, there is a problem with the fix, we still do have a crash there when exiting a scenario where 2vessels are docked
You should remove the two lines

if (body[i]->s0) body[i]->s0 = NULL;
if (body[i]->s1) body[i]->s1 = NULL;

because the s0 and s1 are actually used (when vessels are docked) during the vessel object destruction method occuring at the next code line

thanks

**Comment by spacex15** [comment]
It seems the patch was applied

so I close the issue
