### ISSUE TITLE
Crash to desktop when using too much Time acceleration while flying in atmosphere

### ISSUE THREAD

**Issue by supersonic71** [orbitersim/orbiter#176]
Steps -   
1. Open the scenario DeltaGlider -> Animated Control Surfaces
2. Pitch down the vessel
3. Press [T] multiple times quickly to accelerate time. 

Most of the time it crashes to desktop (no error messages). 

Possible solution - Different limit for max time acceleration when inside atmosphere

**Comment by riojax** [comment]
> Possible solution - Different limit for max time acceleration when inside atmosphere

First, thank you for reporting. About this solution, I think that's a good idea that can be implemented on next patches due that now at very fast sim speeds it can't calculate well and all will a mess, but anyway it shouldn't crash and IMHO this must to be addressed first, for this I pushed the PR #177. Please, can you try it to verify if it's fixed?

**Comment by supersonic71** [comment]
Hi riojax, just tried your branch, can confirm that it no longer crashes.     
Thanks!

**Comment by riojax** [comment]
Nice, thank you 👍
