### ISSUE TITLE
occasional crash on scenario loading in D3d9client

### ISSUE THREAD

**Issue by spacex15** [orbitersim/orbiter#179]
I had an occasional crash in void Scene::SetupInternalCamera(D3DXMATRIX *mNew, VECTOR3 *gpos, double apr, double asp)
at first timestep

I suggest to add a test on camera.vnear on the following line in OVP\D3D9client\scene.cpp
// Something is very wrong... abort...
	if (Camera.hObj_proxy == NULL || Camera.vProxy == NULL ) return;

and change it to
// Something is very wrong... abort...
	if (Camera.hObj_proxy == NULL || Camera.vProxy == NULL || Camera.vNear == NULL) return;

**Comment by riojax** [comment]
Good catch, I will check it a bit and make a PR once tested.
