### ISSUE TITLE
Pads and runways bleed through the ground when adding a normal or bump map

### ISSUE THREAD

**Issue by OvalDreamX** [orbitersim/orbiter#181]
![Clipboard02](https://user-images.githubusercontent.com/71135484/162970209-f9914b71-d51e-437c-9577-89f6d0233e02.png)
![Clipboard03b](https://user-images.githubusercontent.com/71135484/162970229-3a5da83c-92dd-472c-bee2-4baf0a65276c.png)
It does the same whether with custom textures or just baking normals for the default textures

**Comment by jarmonik** [comment]
Fixed in #280
