### ISSUE TITLE
Scenario saved via scenario editor (not quick save) doesn´t show description

### ISSUE THREAD

**Issue by supersonic71** [orbitersim/orbiter#192]
Reposting from https://www.orbiter-forum.com/threads/saved-scenario-doesn%C2%B4t-show-description.40573/
>Fede : 
 When I save via scenario editor (not quicksave), I put a name on the "title of the scenario" and on the description box I put the a brief description of that scenario, (the scenario is saved ok) but when I restart orbiter and select that scenario the description box shows "current state" instead of the description I wrote when I saved the scenario

>Kuddel: 
It's a (small) error in the ScenarioEditors Save function.
The description is there in the scenario file, but it also has a "Help" entry[1] which "overrides" the descrption with the content of the Help (HTML) file
Easiest fix is to open the Scenario-File with Notepad and just remove the line containing "Help CurrentState_img"

**Comment by mschweiger** [comment]
I have submitted a fix for this: pull request #197 
Can you please check if this fixes the problem for you?

**Comment by supersonic71** [comment]
@mschweiger Just tested, it now shows the description.  
Thanks!
