### ISSUE TITLE
Pads and Runways bleed through terrain when d3d9 debug window is open

### ISSUE THREAD

**Issue by OvalDreamX** [orbitersim/orbiter#198]
Like stated in #181 , but it does the same when the d3d9 debug window is open (Ignore weird hangar in front and different concrete textures)
Normal
![Clipboard01](https://user-images.githubusercontent.com/71135484/182620204-5043ec3f-122e-4ed4-8747-a98fbeadfec9.png)
Window open
![Clipboard02](https://user-images.githubusercontent.com/71135484/182620251-e4d25445-fd23-48d9-a59d-29856a200d47.png)

**Comment by jarmonik** [comment]
Fixed in #280
