### ISSUE TITLE
Clicking on D3D7 Configuration options causes crash

### ISSUE THREAD

**Issue by supersonic71** [orbitersim/orbiter#233]
Orbiter-x86 (https://github.com/orbitersim/orbiter/actions/runs/2990259285)
Set Graphics Engine to D3D9Client and restart Orbiter
Now change to D3D7Client, go to Extras tab and click on "D3D7 Graphics Configuration"
![image](https://user-images.githubusercontent.com/17806210/188477685-e656e992-947b-471c-9a6f-81191e82254b.png)
This causes a crash

**Comment by mschweiger** [comment]
I have fixed a few things relating to graphics client selection (issue #228) in thread [228-video_tab_update_on_client_change](https://github.com/orbitersim/orbiter/tree/228-video_tab_update_on_client_change). This wasn't directly related to your issue, but may have fixed it anyway. Could you please check if commit f2c7212 fixes your problem?
