### ISSUE TITLE
Edwards Final Approach [D3D9] [Elevation]

### ISSUE THREAD

**Issue by jarmonik** [orbitersim/orbiter#245]
The Edwards Final Approach scenario under the Antelope Valley folder has two problems while running in D3D9 client. It's works fine in DX7: first, the runway and base tile doesn't load until much closer. Second, the terrain collision happens while above the real ground just about 100m.

**Comment by mschweiger** [comment]
Has this problem been fixed with PR #276?

**Comment by jarmonik** [comment]
Yes, I believe so. Closing...
