### ISSUE TITLE
Use spectral type information in Hipparcos data to apply colour variations to stars on celestial sphere

### ISSUE THREAD

**Issue by mschweiger** [orbitersim/orbiter#257]
The Hipparcos catalog used to generate the (single-pixel) star renderings on the celestial sphere contains spectral type information which could be used to add colour tints to the rendered pixels.

Also take the opportunity to provide a more complete version of the catalog (currently, only ~40000 entries are used).

**Comment by jarmonik** [comment]
Hi,
Sorry about delay. I have reviewed the changes and they look good to me. I don't see a problem with a unit size celestial sphere. So far, all my test runs have passed fine. Nice work.
