### ISSUE TITLE
Location of compilation products

### ISSUE THREAD

**Issue by GLS-SSV** [orbitersim/orbiter#263]
I'm using CMake to generate a VS2017 solution to compile Orbiter. Currently the "compilation products" (dll, exe...) are placed in folders named for the current build. This required me to make a small script to move the files to the correct folders.
But now I see that the D3D9 products already show up in correct folders, ready to use. Could the rest of the products also be placed in their final locations, like D3D9?

**Comment by mschweiger** [comment]
Do you mean the fact that binaries end up in Release/Debug subdirectories? This is a known problem of the VS generators (owing to the fact that the VS generators are multi-configuration generators, so this is their way to keep the different configurations separate). My suggestion would be to use a single-configuration generator like Ninja, which doesn't have that problem. Ninja is already built into VS2019. With VS2017, you would have to install Ninja yourself. You may also have to install vspkg to set the compiler toolchain to the desired configuration. Once Ninja is installed, you should be able to select it as the preferred generator when configuring cmake.

**Comment by mschweiger** [comment]
A potentially simpler solution is to run Orbiter from the install directory rather than the build directory. Everything should be in the right place in the install directory.

**Comment by GLS-SSV** [comment]
(sorry it took this long to come back to this one)
Thanks for the answer. I can't make heads or tails of Ninja+CMake, so I'll just keep my current "solution" until I upgrade my Visual Studio.
