### ISSUE TITLE
oapiCameraRotationMatrix missing documentation

### ISSUE THREAD

**Issue by spacex15** [orbitersim/orbiter#278]
title says it all !

**Comment by schnepe2** [comment]
If I had to guess, it would be somethig like this:
```
	/**
	 * \brief Returns a rotation matrix which performs the transformation
	 *   from the camera rotation into global coordinates.
	 * \param rmat pointer to a matrix receiving the rotation data
	 * \sa oapiCameraGlobalPos, oapiCameraGlobalDir
	 */
OAPIFUNC void oapiCameraRotationMatrix (MATRIX3 *rmat);
```
But @mschweiger has to do the `\ref` and check if this is **really** what it does 😀 

**And yes**, no documentation is bad - but no documentation is better than wrong documentation!

**Comment by mschweiger** [comment]
Couldn't have formulated it better myself, so I took the liberty of using your suggestion verbatim. :+1:
