### ISSUE TITLE
Shuttle-A Payload shadows wrong in initial (landed) state

### ISSUE THREAD

**Issue by schnepe2** [orbitersim/orbiter#328]
Initial rendering of the shadows seem to behave very odd.
When you run the attached scenario and rotate a bit around you will see what I mean.
It first looked like a rendering issue, but it seems more a "initial-vessel-state" issue.

Scenario: [ShadowIssueTest.scn.txt](https://github.com/orbitersim/orbiter/files/10326106/ShadowIssueTest.scn.txt) [\*]
[\*] had to rename it to .txt

### Further investigation (by Jarmo) found the following:
It looks like the problem could be in Orbiter Core. Surface normals don't match, for some reason the normals for payload canisters are misplaced. Problem seems to be in `HorizonInvRot()`.

The problem mentioned above is tied to vessel status. As long as it remains "landed" `HorizonInvRot()` is incorrect for attachments but becomes correct when vessel status changes to "active".

### Images of issue / behaviour
The following images show the normals as vectors from Vessel-Shadow-Render code (something like):
```cpp
	VECTOR3 hn, hnp = vessel->GetSurfaceNormal();
	vessel->HorizonInvRot(hnp, hn);
	AddDebugVector(hn, name); // <= debugging
```

Initial (direct after scenario start):
![0000](https://user-images.githubusercontent.com/18400313/210107503-bf0c97f9-b203-4e59-adcc-7c58fd515de6.jpg)

Once you apply a little thrust (to shake the ship and exit "landed" state) the normals snap into correct place:
![0001](https://user-images.githubusercontent.com/18400313/210107513-f1455e48-9900-446e-91c7-109d98cc75b7.jpg)

For reference see https://www.orbiter-forum.com/threads/d3d9client-development.16787/post-604662 and following posts.

**Comment by jarmonik** [comment]
I was looking into this and couldn't reproduce the problem anymore. Could someone double check ?

**Comment by jarmonik** [comment]
Correction. I can reproduce the problem with "Stencil" shadows. Looking into it.
