### ISSUE TITLE
C++ standard conformance

### ISSUE THREAD

**Issue by dimitry-ishenko** [orbitersim/orbiter#338]
Looking through the code I see things like:

* Identifiers starting with underscore (in violation of [[lex.name]/3](https://timsong-cpp.github.io/cppwp/n4868/lex.name#3))
* Use of `char*` instead of `std::string`
* Use of windows-specific functions instead of standard library
* Use of home-grown solutions instead of standard library

I also can't tell which version of C++ standard the code follows (other than the [D3D9 client](https://github.com/orbitersim/orbiter/blob/bf1e0fd6958c6eb9d3f6289794d96795029af407/OVP/D3D9Client/CMakeLists.txt#L7) and some [tileedit](https://github.com/orbitersim/orbiter/blob/bf1e0fd6958c6eb9d3f6289794d96795029af407/Utils/tileedit/qt/src/CMakeLists.txt#L4) utility).

As a first step I would recommend picking a standard for the project, so that contributors know not to exceed it. 

Luckily, MSVC (VS 2019 16.10) has a full support for the [C++20 core language](https://en.cppreference.com/w/cpp/compiler_support#cpp20) and also the [Standard Library](https://en.cppreference.com/w/cpp/compiler_support#C.2B.2B20_library_features). So, this should be pretty easy - pick C++20 as the standard for the project.

Next is, obviously, would be to incrementally update the code-base to conform to the standard, as well as replace any windows-specific functions with the STL ones.

This will also help make the code easier to port to other platforms, such as Linux and MacOS.

**Comment by n7275** [comment]
If you are interested in working on this, it would be worthwhile to collaborate with https://github.com/TheGondos who was working on some of the same things, especially some of the Windows-specific stuff.

I would do this as incrementally as possible so that anyone that is working on longer-running projects has less to worry about by way of merge-conflicts.

**Comment by dimitry-ishenko** [comment]
@n7275 yeah that sounds good. Unfortunately, I don't see any changes in that repo landing in here. Did I miss something?

**Comment by dimitry-ishenko** [comment]
Another thing is the coding style. Or, rather, lack of it... 😅 Is there one?

**Comment by maxq519** [comment]
Just remember, a lot of us aren't professional programmers.  Might keep that in mind when writing...

**Comment by dimitry-ishenko** [comment]
@maxq519 neither am I 😄. I am talking about a simple document with things like:

* Use `.h` extension for header files and `.cpp` for source files.
* Use 4 spaces for indentation.
* Use `#define` guards in headers.
* Use camel notation for functions.
* ...
* ...

Nothing complicated.

**Comment by dimitry-ishenko** [comment]
@Xyon let me know what you think about these patches. I've got about 50 of them queued up, but I wanted to release them piece-meal, so as not to overwhelm anyone.

**Comment by n7275** [comment]
I think if you want to make a sweeping change to the code style, that doesn't change anything functional, make it as one giant commit. If we ever need to look back through the commit log it will be way more clear, say 5 years down the road. As part of closing this issue you can/should probably rev the contribution guide to match.

**Comment by dimitry-ishenko** [comment]
@n7275 I can do one giant commit. I was just thinking for the purposes of future bisects to track down bugs, it would be better to have small commits. Plus, I didn't want to overwhelm anyone. 😄 

And just to clarify, there aren't any functional changes to the code. The only things I am doing is fixing things considered invalid by current C++ standards.

Or, maybe what I can do a one giant PR that consists of a bunch of small patches. This way it can be approved once, but still gives an option of running git bisect in the future.

**Comment by Xyon** [comment]
One giant commit is definitely harder to read through for seeing the changes, which is definitely going to help for my purposes :P

**Comment by dimitry-ishenko** [comment]
@Xyon I've got a bunch more patches ready to go. All small. Should I go ahead and add them to the PR #342 or would you rather want a separate PR?

**Comment by Xyon** [comment]
Eh, sod it, lob them in 342

**Comment by dimitry-ishenko** [comment]
@Xyon done. Now the real work can start... 😈
