### ISSUE TITLE
oapiLoadTexture() ignores texture flags

### ISSUE THREAD

**Issue by CaptainSwag101** [orbitersim/orbiter#340]
In the function oapiLoadTexture() in OrbiterAPI.cpp, I believe that the bitwise function performed on the image flags is incorrect. Currently the flags are manipulated like so:

`8 & (dynamic ? 3:0)`

However, this means that the image flags for any texture loaded via this function will ***always*** be un-set, because (8 & 3) or (8 & 0) will only ever result in 0. I do not believe this was the intended behavior, because no bitwise math is necessary to force-disable special texture flags; the value could just be set to 0 explicitly when passed into gc->clbkLoadTexture().

I am not entirely sure, but by consulting the associated GraphicsAPI.h file, what I suspect this code was meant to do was to use bitwise OR rather than AND:

`8 | (dynamic ? 3:0)`

Which would always set bit 3 of the image flags (setting the texture as a global resource manageable by the graphics client), and then if the image is dynamic, additionally setting bits 0 and 1 (forcing texture creation in system memory, and forcing decompression even if the texture format is supported by the device).

This would be a very simple pull request to make, but since I am unfamiliar with the Orbiter codebase, I would rather start a discussion about this first with people who would have a better idea of what this function ought to be doing, rather than blindly making changes based on an assumption that may or may not be correct, or could potentially break things I'm not aware of.

**Comment by jarmonik** [comment]
Yes, you are right there. Has there been recent changes to it ? If it's been there for a decades then how many add-ons depends on faulty operation ? Should we leave it there until API cleanup.

**Comment by CaptainSwag101** [comment]
> Yes, you are right there. Has there been recent changes to it ? If it's been there for a decades then how many add-ons depends on faulty operation ? Should we leave it there until API cleanup.

I checked the git blame on that function, it appears to have been this way since the code was imported from the Orbiter SVN repository in 2021. So it seems likely that this function has been bugged for a very long time. I'm not sure when an API cleanup would happen, or what kinds of addons might rely on this faulty behavior.

**Comment by jarmonik** [comment]
oapiLoadTexture() is very much made obsolete/deprecated by oapiLoadSurfaceEx(), so, it's likely that we keep the oapiLoadTexture() as it is for a backwards compatibility reasons with no changes to it. oapiLoadSurfaceEx() has much wider functionality.
