### ISSUE TITLE
Add system requirements

### ISSUE THREAD

**Issue by Miner34dev** [orbitersim/orbiter#350]
I noticed Orbiter has no system requirements except for ram and disk space, so if somebody wants to know if their PC is enough powerful to run it, the only way is to install it.

There is a requirements table:

|  | Minimum requirements | Recommended requirements |
| ---- | ---- | ---- |
| RAM: | 4GB | 8GB |
| CPU: | Dual Core |  |
| GPU: | 200 GFlops | 500 GFlops |
| Disk: | 4GB of free space | 10GB of free space |

Is it ok?

**Comment by jarmonik** [comment]
Orbiter can adapt to various system configurations by toggling some features on or off. I get about 60 fps on old Intel HD graphics 4000 laptop if I disable anti-aliasing and reflections and post-processing and use a lower quality atmospheric effects. With my gaming machine I get about 1000 fps with max settings.

**Comment by Miner34dev** [comment]
Ok, i updated the requirements, but what about your laptop's cpu?

**Comment by jarmonik** [comment]
i3-3217U  Orbiter doesn't cause much CPU load. Graphics is the bottle neck.
