### ISSUE TITLE
Add missing MicroTextures

### ISSUE THREAD

**Issue by riojax** [orbitersim/orbiter#351]
As the awesome @jarmonik 's D3D9Client was included and the Config/MicroTex.cfg references the missing MicroTextures. We can add them to the main Textures folder?

P.S. The missing textures are
Textures/D3D9Mars_A.dds
Textures/D3D9Mars_B.dds
Textures/D3D9Moon_A.dds
Textures/D3D9Moon_B.dds
Textures/D3D9Moon_C.dds
Textures/D3D9Moon_C2.dds

**Comment by Miner34dev** [comment]
Where can i find them?

**Comment by riojax** [comment]
The last link on http://jarmonik.org

[Direct download](https://orbiter-mods.com/mod/44)

**Comment by riojax** [comment]
Ok, I created the PR #352 with the missing files

**Comment by Xyon** [comment]
@jarmonik I guess these are yours, are you happy with us pulling them into the repo?

**Comment by jarmonik** [comment]
Yes, they can be included in the repo.
