### ISSUE TITLE
Virtual cockpit

### ISSUE THREAD

**Issue by MSob7i** [orbitersim/orbiter#376]
hi guys
i am a big fan to orbiter
my dream is to build a physical virtual cockpit for XR2 and Delta glider iv …
i need to control every button on the panels by physical button
i am not talking here about hardware i am talking about there is no setting in the launcher that i can maping controls via external joystick buttons for example
i need more axis trans, rot, hover engines, rev .... to control via joystick
i need to connect more than one joystick
i need digital outputs that i can use to indicator leds
sorry about my english :)
hope to hear from u soon

**Comment by jarmonik** [comment]
Find existing solutions from Orbiter Forum.
