### ISSUE TITLE
License Contradiction Between Repository and Official Website

### ISSUE THREAD

**Issue by TChapman500** [orbitersim/orbiter#40]
So, the website has a [Terms of Use](http://orbit.medphys.ucl.ac.uk/terms.html) page that seems to contradict the repository's [License](https://github.com/orbitersim/orbiter/blob/master/LICENSE) page.  For example, the former prohibits making any sort of money from the use of the software while the latter permits the user to use the software as he/she desires without any restrictions except to (a) include the copyright notice and (b) to include the permission notice.

**Comment by mschweiger** [comment]
I don't see a problem. These are two different things. The website refers to Orbiter 2016, which was and is closed-source. It comes with its own non-open license. 

The repository refers to an open-source project with MIT license. True, they are based on very similar code bases, but that is rather incidental.

So in short, if you want to make money from Orbiter, you better go for the source repository.

I admit that the coexistence of the two projects is a bit confusing, so I'll take down the Orbiter website when I get time.

**Comment by TChapman500** [comment]
You're going to take down the whole website?

**Comment by Ytrog** [comment]
> I don't see a problem. These are two different things. The website refers to Orbiter 2016, which was and is closed-source. It comes with its own non-open license.
> 
> The repository refers to an open-source project with MIT license. True, they are based on very similar code bases, but that is rather incidental.
> 
> So in short, if you want to make money from Orbiter, you better go for the source repository.
> 
> I admit that the coexistence of the two projects is a bit confusing, so I'll take down the Orbiter website when I get time.

Did you already do that? It seems all download mirrors are down 😢

**Comment by supersonic71** [comment]
@Ytrog 4th mirror is working
