### ISSUE TITLE
No Lua vessel callbacks or oapi methods available to read/write vessel state variables to scenario files.

### ISSUE THREAD

**Issue by ThChicken** [orbitersim/orbiter#405]
There do not appear to be Lua vessel callbacks equivalent to clbkSaveState(scn) that can be overloaded to allow custom vessel status variables to be saved to the scenario file, or clbkLoadStateEx(scn) to read custom vessel status variables from the scenario file.

Without these callbacks or equivalents, custom vessel states for Lua script vessels cannot be saved or read from the scenario files.

**Comment by schnepe2** [comment]
...working on that 😉
[Detailed discussion here](https://www.orbiter-forum.com/threads/the-future-of-lua-with-orbiter-is-it-at-a-dead-end.41527/post-615019)
