### ISSUE TITLE
Vessel Lighting issue, possibly dependant on distance from sun

### ISSUE THREAD

**Issue by n7275** [orbitersim/orbiter#417]
![image](https://github.com/orbitersim/orbiter/assets/100335/c3712ddf-beb2-4408-a030-5b437bbd118d)
![image](https://github.com/orbitersim/orbiter/assets/100335/20b0f6d2-4feb-47cf-85c6-7fd25ad48a01)
![image](https://github.com/orbitersim/orbiter/assets/100335/4c4f662d-129a-4862-837d-8687a508f10e)

I first noticed this in orbit around Mercury. Vessels receive light from local light sources and from planet-shine, but not from the sun.

This appears to occur approximately 90Gm and less from the sun, although I couldn't determine the exact distance.

When crossing from a "low altitude" (<85Gm) back to a "higher altitude" (>85Gm), lighting from the sun does not resume, instead the "Ghost Ship" (images 2 and 3) or intermittently, a normal looking mesh with no sun lighting.

This effect persists: after reloading the scenario (current state), after closing and re-opening Orbiter and launching (current state).

The effect is cleared by loading a different scenario.

Can anyone else reproduce this?

**Comment by jarmonik** [comment]
Ok, thanks. Will look into it.

**Comment by n7275** [comment]
The way that the issue persists even on reloading Orbiter, makes me think that there is some variable that has a bad combination of "not initialized by a constructor" and "not freed from memory by a destructor".

But that's a complete guess.
