### ISSUE TITLE
Very slow framerate and terrain graphics issues

### ISSUE THREAD

**Issue by ThChicken** [orbitersim/orbiter#419]
I have been experiencing very low frame rates (1-3 seconds per frame) and terrain textures are not being rendered in Orbiter v.240117 as well as with previous builds. This occurs on a fresh install of 32-bit Orbiter v.240117 with no add-ons. The behavior is described here with some screenshots:

https://www.orbiter-forum.com/threads/the-future-of-lua-with-orbiter-is-it-at-a-dead-end.41527/page-4#post-615258

A fresh install of Orbiter 2016 runs very well on the same hardware and terrain graphics render correctly:

https://www.orbiter-forum.com/threads/the-future-of-lua-with-orbiter-is-it-at-a-dead-end.41527/page-4#post-615262

I am running both on Linux Mint 21.3 Virginia under Wine version 9.0, but experienced this behavior under earlier versions of this OS and Wine.

I cannot currently test the 64-bit version as the latest build crashes on Linux (I believe this is already on your radar but I'll open this under a new issue):

https://www.orbiter-forum.com/threads/problem-with-latest-orbiter-build-on-linux.41564/#post-615278

**Comment by jarmonik** [comment]
You have obviously forgotten to install planetary textures. I will add a popup window to notify user about missing textures.
I haven't had any frame rate issues on Windows running at 600fps and I don't see any indication of any problems pointing to the Orbiter here. No action required.
