### ISSUE TITLE
Problem with Orbiter build 240117 Crashing on Linux under DX9

### ISSUE THREAD

**Issue by ThChicken** [orbitersim/orbiter#420]
Orbiter 240117 crashes under DX9. Behavior is described in these threads:

https://www.orbiter-forum.com/threads/the-future-of-lua-with-orbiter-is-it-at-a-dead-end.41527/page-4#post-615268

https://www.orbiter-forum.com/threads/problem-with-latest-orbiter-build-on-linux.41564/#post-615278

It also doesn't seem that there is a DX7 client for the 64-bit version. 

Note this is a separate issue not related to Issue #419.

**Comment by vineet131** [comment]
You're compiling on Linux? I thought that wasn't fully supported yet

**Comment by ThChicken** [comment]
> You're compiling on Linux? I thought that wasn't fully supported yet

No. I am running the executables on a Linux OS using Wine. Orbiter 2016 runs just about perfectly. OpenOrbiter...not so much.

**Comment by dimitry-ishenko** [comment]
> You're compiling on Linux? I thought that wasn't fully supported yet

It can be done with wine fairly easily.

**Comment by jarmonik** [comment]
The problem is not in D3D9 this is a Linux failure. When I got time, I'll alter the initialization to be more Linux friendly.

**Comment by jarmonik** [comment]
This problem appears to be solved already.

**Comment by ThChicken** [comment]
What was the solution?

**Comment by jarmonik** [comment]
I don't know exactly. Solution might be telling the wine to use dxvk instead of something else for rendering. But anyway, I'll add the Kuddel's solution to the client so that this issue wont bother anymore.

**Comment by jarmonik** [comment]
Fix for this is now uploaded.
