### ISSUE TITLE
DrawOrbits module (sometimes black screen)

### ISSUE THREAD

**Issue by MishaPhysics** [orbitersim/orbiter#435]
Actually it's not so important and urgent, but for a future... I think this module could be improved a bit (for example for the 2024 release), namely adding some display options, and maybe (or not) separating it from the default planetarium mode. Sometimes I get a black screen for some distance. I've tried it with the last x86 build.

![1](https://github.com/orbitersim/orbiter/assets/104359915/6a52bb12-a142-4eec-bd65-8a6ce757db49)
![2](https://github.com/orbitersim/orbiter/assets/104359915/65a915ba-8c20-4555-9780-1fef68f58149)

**Comment by jarmonik** [comment]
Is the black screens issue fixed ?

**Comment by MishaPhysics** [comment]
I've tried several times to reproduce that black screen in the latest v240310 build, but it doesn't happened. But now I can't even reproduce it in the previous build where I made the screenshots above. I let you know if this happens again in the new build.

**Comment by MishaPhysics** [comment]
Although there are two errors in Orbiter.log (in the new build), and the second seems to be related to the DrawOrbits module, but I'm not sure if it's related to that black screen:
000157.848: D3D9ERROR: UnDeleted Surfaces(s) Detected 1... Releasing...
000157.849: D3D9ERROR: Surface [samples\DrawOrbits\Orbits.dds] (128, 64)

**Comment by MishaPhysics** [comment]
I think I have to close this issue since I don't notice the problem in the last build where some changes were made. Although a separation this module from the default planetarium mode could be a not bad idea with some improvements of this module in the future.
