### ISSUE TITLE
Documentation rework - part 1: Setup and conversion

### ISSUE THREAD

**Issue by GLS-SSV** [orbitersim/orbiter#439]
The first of a pair of tickets for tracking (1) the conversion of the existing documentation to LaTeX and then (2) updating and correcting the new documentation, solving the existing documentation build issues and replacing binary source files with text files.

- [X] Definition of styles
Common file created.
Orbiter logo for cover defined.
The original font for the text is "Liberation Serif", a free alternative to "Times New Roman". Another font used is Georgia. Current font is Helvetica.
Alert and code boxes defined.

- [X] Orbiter User Manual
Mostly complete.

- [X] Orbiter Developer Manual
Mostly complete.

- [X] Orbiter Technical Reference
Mostly complete.

**Comment by GLS-SSV** [comment]
PR #438

**Comment by GLS-SSV** [comment]
Updated first post.
Current results:
[Orbiter User Manual.pdf](https://github.com/orbitersim/orbiter/files/14488624/Orbiter.User.Manual.pdf)
[Orbiter Developer Manual.pdf](https://github.com/orbitersim/orbiter/files/14488621/Orbiter.Developer.Manual.pdf)

**Comment by ThChicken** [comment]
Are other documents like 3DModel.pdf in OrbiterSDK/doc being addressed by this? It seems that Chapter 7 of the Developer Manual incorporates the information in this file. 

I am aware of one typo on page 5 of 3DModel.pdf, under Mesh File, that the example mesh file starts with the header "MESHX", which seems to have been replaced with "MSHX1" at some point in Orbiter history. Attempting to work with a mesh file using the MESHX header doesn't work, and only by looking at other meshes was this determined.

If there is a better place to post this, let me know and I'll put it there.

**Comment by GLS-SSV** [comment]
Late, but better than never...


> Are other documents like 3DModel.pdf in OrbiterSDK/doc being addressed by this? It seems that Chapter 7 of the Developer Manual incorporates the information in this file.

Yes, the plan is to remove all the files in Orbitersdk/doc folder and replace them with the Orbiter Developer Manual.



> I am aware of one typo on page 5 of 3DModel.pdf, under Mesh File, that the example mesh file starts with the header "MESHX", which seems to have been replaced with "MSHX1" at some point in Orbiter history. Attempting to work with a mesh file using the MESHX header doesn't work, and only by looking at other meshes was this determined. If there is a better place to post this, let me know and I'll put it there.

What was done so far was the conversion of the existing files into the 3 docs (and the occasional typo fix, like that one), and part 2 will now update and correct bugs. Issues should be reported in the second ticket (https://github.com/orbitersim/orbiter/issues/440), so it is all in one place.




> Also - a lot of effort has been put into enabling Lua Scripting to make vessel add-ons as an alternative to compiling modules, but there is no mention of Lua Scripting in the Orbiter Developer Manual content outline. There is a chapter 14 titled scripting interface in the User Manual, but I think that may be just for playback and other features?

In the conversion I kept things mostly as they were in the original docs, leaving the updating and additions for later, and AFAIR there was no chapter for Lua in the original doc.
The Lua documentation should also be part of the Orbiter Developer Manual, but it seems that part is going a different way....
