### ISSUE TITLE
Documentations to 3d cockipt

### ISSUE THREAD

**Issue by daniele777** [orbitersim/orbiter#441]
Hi guys there is document
For understand where to start to improove 3d cockipt of deltaglider?

**Comment by GLS-SSV** [comment]
Hi!
There is documentation explaining the workings of (generic) virtual cockpits (and that is currently being improved), but there is nothing specific about any vessel, as each vessel will have its own buttons, lights, etc.

**Comment by daniele777** [comment]
How to open current vessel graphics?

**Comment by GLS-SSV** [comment]
I think you should post in the forum, as these tickets are not the correct place to request help.

**Comment by daniele777** [comment]
Thx
