### ISSUE TITLE
Lighting issue when Neptune or Uranus (and Titan, and maybe others?) are the primary gravity reference.

### ISSUE THREAD

**Issue by n7275** [orbitersim/orbiter#466]
I've been doing some testing, and I've discovered a strange lighting bug:

If you look very closely there is a Deltaglider in this image...

![1719180483418](https://github.com/orbitersim/orbiter/assets/100335/680c61ab-0882-4814-bf73-0bbeba4e5c29)

Easy way to replicate: put yourself in an orbit around Uranus or Neptune (and their moons). The problem goes away as soon as the gravity reference switches to the sun, and does not require a reload.

Buuuuut.....

Reloading fixes the "ghost ship" issue, and gives you a "no sunlight" condition.

![1719180947700](https://github.com/orbitersim/orbiter/assets/100335/cdd1e116-b844-433e-9f51-ad6e896052ad)

It appears very similar to [this issue](https://github.com/orbitersim/orbiter/issues/417) but I can't find a connection. 

I tested the rest of the solar, and Jupiter, Saturn, Mars, Earth, and a bunch of their moons all seem fine. Titan has planet-shine but no sunlight.

I think there is some edge-case where the "are we in sunlight" condition isn't being met. I am creating a post on the forum: https://www.orbiter-forum.com/threads/orbiter-2024-launch-readiness.41630/post-620422

**Comment by n7275** [comment]
@jarmonik,

I'm trying to compare these two functions:

https://github.com/orbitersim/orbiter/blob/4a00732120be873113012d316d618af7712ed2f8/OVP/D3D7Client/VVessel.cpp#L664

https://github.com/orbitersim/orbiter/blob/4a00732120be873113012d316d618af7712ed2f8/OVP/D3D9Client/VVessel.cpp#L1463

I presume the reason that the D3D9 version has so much less code in it, is that it's been moved to other functions?

I almost wonder if we need a really robust solution where we check every body for blocking the sun (even if it's less performant to do it that way). It just seems like there are so many edge cases.

**Comment by n7275** [comment]
This might be useful information: 
![image](https://github.com/orbitersim/orbiter/assets/100335/255748c7-a891-4ab7-a5a7-707b2c85316f)

**Comment by TheGondos** [comment]
Can repro this on OpenOrbiter. Playing with D9D9 Debug Controls, it seems to happen only with the "metalness PBR" shader, not with the "PBR (Old)" one.
