### ISSUE TITLE
Crash protection after deleting the last vessel.

### ISSUE THREAD

**Issue by MishaPhysics** [orbitersim/orbiter#495]
It's known that Orbiter crashes to desktop when trying to delete the last vessel from simulation using Scenario Editor. It would be nice to protect the last vessel from deleting.

**Comment by TheGondos** [comment]
That should be straightforward, I can have a look at it

**Comment by n7275** [comment]
I'm okay merging this for the 2024 release. Let's just make sure that it
doesn't effect deallocation, or deleation of vessels by Orbiter on
simulation close.

**Comment by TheGondos** [comment]
The change only impacts the scenario editor when clicking the delete button, nothing was changed in the Orbiter core.
