### ISSUE TITLE
Degree sign in DrawOrbits

### ISSUE THREAD

**Issue by GLS-SSV** [orbitersim/orbiter#510]
The degree sign in the captions of DrawOrbits shows messed up.
![draworbits_vessels](https://github.com/user-attachments/assets/45b1c632-af21-4b6f-a7dc-aca41daf1ca5)
Looks like UTF-8 encoding is not being respected.

**Comment by MishaPhysics** [comment]
Also, the DrawOrbits information in the Module tab requires to be updated, since it says "Requires Orbiter Beta 2016 and D3D9Client. (I checked the OpenOrbiter 2024 RC1.) 

And I propose to separate the DrawOrbits module from the Planetarium mode (F9 key).

**Comment by n7275** [comment]
This can now be closed

**Comment by GLS-SSV** [comment]
Fixed in #525
