### ISSUE TITLE
Virtual cockpit for xr2

### ISSUE THREAD

**Issue by MSob7i** [orbitersim/orbiter#54]
Looking forward orbiter to have more digital and analog controls
Multi monitoring
separated monitoring for every monitor in the panals and HUD

**Comment by JDat** [comment]
Check how this is implemented in samples/DeltaGlider. It is vessel specific, so no need to change core.

**Comment by Xyon** [comment]
The XR2 isn't part of the core Orbiter solution - any development of a VC for this or any other vessel will need to take place in the code supplied by its developer.
